# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logcosh <- function(x) {
    .Call('_unbiasedpathsampling_logcosh', PACKAGE = 'unbiasedpathsampling', x)
}

gaussian_max_couplingC <- function(mu1, mu2, Sigma1, Sigma2) {
    .Call('_unbiasedpathsampling_gaussian_max_couplingC', PACKAGE = 'unbiasedpathsampling', mu1, mu2, Sigma1, Sigma2)
}

gaussian_max_coupling_cholesky <- function(mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2) {
    .Call('_unbiasedpathsampling_gaussian_max_coupling_cholesky', PACKAGE = 'unbiasedpathsampling', mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2)
}

xbeta_2 <- function(X, beta) {
    .Call('_unbiasedpathsampling_xbeta_2', PACKAGE = 'unbiasedpathsampling', X, beta)
}

w_rejsamplerC <- function(beta1, beta2, X) {
    .Call('_unbiasedpathsampling_w_rejsamplerC', PACKAGE = 'unbiasedpathsampling', beta1, beta2, X)
}

w_max_couplingC <- function(beta1, beta2, X) {
    .Call('_unbiasedpathsampling_w_max_couplingC', PACKAGE = 'unbiasedpathsampling', beta1, beta2, X)
}

estimator_bin <- function(c_chains, component, lower, upper, k, K) {
    .Call('_unbiasedpathsampling_estimator_bin', PACKAGE = 'unbiasedpathsampling', c_chains, component, lower, upper, k, K)
}

#' @export
gradlognormal <- function(x, mean, precision) {
    .Call('_unbiasedpathsampling_gradlognormal', PACKAGE = 'unbiasedpathsampling', x, mean, precision)
}

rinvgaussian_c <- function(n, mu, lambda) {
    .Call('_unbiasedpathsampling_rinvgaussian_c', PACKAGE = 'unbiasedpathsampling', n, mu, lambda)
}

rinvgaussian_coupled_c <- function(mu1, mu2, lambda1, lambda2) {
    .Call('_unbiasedpathsampling_rinvgaussian_coupled_c', PACKAGE = 'unbiasedpathsampling', mu1, mu2, lambda1, lambda2)
}

sigma_ <- function(X, w) {
    .Call('_unbiasedpathsampling_sigma_', PACKAGE = 'unbiasedpathsampling', X, w)
}

m_sigma_function_ <- function(omega, X, invB, KTkappaplusinvBtimesb) {
    .Call('_unbiasedpathsampling_m_sigma_function_', PACKAGE = 'unbiasedpathsampling', omega, X, invB, KTkappaplusinvBtimesb)
}

xbeta_ <- function(X, beta) {
    .Call('_unbiasedpathsampling_xbeta_', PACKAGE = 'unbiasedpathsampling', X, beta)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('_unbiasedpathsampling_rmvnorm', PACKAGE = 'unbiasedpathsampling', nsamples, mean, covariance)
}

rmvnorm_cholesky <- function(nsamples, mean, cholesky) {
    .Call('_unbiasedpathsampling_rmvnorm_cholesky', PACKAGE = 'unbiasedpathsampling', nsamples, mean, cholesky)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('_unbiasedpathsampling_dmvnorm', PACKAGE = 'unbiasedpathsampling', x, mean, covariance)
}

dmvnorm_cholesky_inverse <- function(x, mean, cholesky_inverse) {
    .Call('_unbiasedpathsampling_dmvnorm_cholesky_inverse', PACKAGE = 'unbiasedpathsampling', x, mean, cholesky_inverse)
}

rnorm_reflectionmax_ <- function(mu1, mu2, Sigma_chol, inv_Sigma_chol) {
    .Call('_unbiasedpathsampling_rnorm_reflectionmax_', PACKAGE = 'unbiasedpathsampling', mu1, mu2, Sigma_chol, inv_Sigma_chol)
}

